### ISSUE TITLE
Move this to Labs

### ISSUE THREAD

**Issue by adamralph** [Particular/NsbBootstrapper#2]

**Comment by adamralph** [comment]
@colin-higgins @johnsimons @petersgiles any opposition?

**Comment by petersgiles** [comment]
no opposition here

**Comment by colin-higgins** [comment]
none here

**Comment by adamralph** [comment]
@colin-higgins @johnsimons @petersgiles done

I'm not sure if you all have (or which of you want) access in the Labs org. If you don't have sufficient permissions, ping me and I'll add you.
